project_id = "vdisgwqubmbcdumovzzg"

[functions.scan-receipt]
verify_jwt = false

[functions.generate-recipes]
verify_jwt = false

[functions.run-ocr]
verify_jwt = false

[functions.parse-receipt]
verify_jwt = false

[functions.ocr-debug]
verify_jwt = false